version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    image: fooddeliverybackend:latest
    container_name: backend
    environment:
      - NODE_ENV=production
